/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AComIdAsVal extends PComIdAsVal
{
    private TId _id_;
    private final LinkedList _asValue_ = new TypedLinkedList(new AsValue_Cast());

    public AComIdAsVal()
    {
    }

    public AComIdAsVal(
        TId _id_,
        List _asValue_)
    {
        setId(_id_);

        {
            this._asValue_.clear();
            this._asValue_.addAll(_asValue_);
        }

    }
    public Object clone()
    {
        return new AComIdAsVal(
            (TId) cloneNode(_id_),
            cloneList(_asValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComIdAsVal(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getAsValue()
    {
        return _asValue_;
    }

    public void setAsValue(List list)
    {
        _asValue_.clear();
        _asValue_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_asValue_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_asValue_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _asValue_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class AsValue_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PAsValue node = (PAsValue) o;

            if((node.parent() != null) &&
                (node.parent() != AComIdAsVal.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AComIdAsVal.this))
            {
                node.parent(AComIdAsVal.this);
            }

            return node;
        }
    }
}
