/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AForStatement extends PStatement
{
    private TId _fId_;
    private TId _iId_;
    private PStatement _statement_;

    public AForStatement()
    {
    }

    public AForStatement(
        TId _fId_,
        TId _iId_,
        PStatement _statement_)
    {
        setFId(_fId_);

        setIId(_iId_);

        setStatement(_statement_);

    }
    public Object clone()
    {
        return new AForStatement(
            (TId) cloneNode(_fId_),
            (TId) cloneNode(_iId_),
            (PStatement) cloneNode(_statement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForStatement(this);
    }

    public TId getFId()
    {
        return _fId_;
    }

    public void setFId(TId node)
    {
        if(_fId_ != null)
        {
            _fId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _fId_ = node;
    }

    public TId getIId()
    {
        return _iId_;
    }

    public void setIId(TId node)
    {
        if(_iId_ != null)
        {
            _iId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _iId_ = node;
    }

    public PStatement getStatement()
    {
        return _statement_;
    }

    public void setStatement(PStatement node)
    {
        if(_statement_ != null)
        {
            _statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _statement_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_fId_)
            + toString(_iId_)
            + toString(_statement_);
    }

    void removeChild(Node child)
    {
        if(_fId_ == child)
        {
            _fId_ = null;
            return;
        }

        if(_iId_ == child)
        {
            _iId_ = null;
            return;
        }

        if(_statement_ == child)
        {
            _statement_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_fId_ == oldChild)
        {
            setFId((TId) newChild);
            return;
        }

        if(_iId_ == oldChild)
        {
            setIId((TId) newChild);
            return;
        }

        if(_statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

    }
}
