/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AListStatement extends PStatement
{
    private TId _id_;
    private PExpression _inBr_;
    private PExpression _outBr_;

    public AListStatement()
    {
    }

    public AListStatement(
        TId _id_,
        PExpression _inBr_,
        PExpression _outBr_)
    {
        setId(_id_);

        setInBr(_inBr_);

        setOutBr(_outBr_);

    }
    public Object clone()
    {
        return new AListStatement(
            (TId) cloneNode(_id_),
            (PExpression) cloneNode(_inBr_),
            (PExpression) cloneNode(_outBr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListStatement(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public PExpression getInBr()
    {
        return _inBr_;
    }

    public void setInBr(PExpression node)
    {
        if(_inBr_ != null)
        {
            _inBr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _inBr_ = node;
    }

    public PExpression getOutBr()
    {
        return _outBr_;
    }

    public void setOutBr(PExpression node)
    {
        if(_outBr_ != null)
        {
            _outBr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _outBr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_inBr_)
            + toString(_outBr_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_inBr_ == child)
        {
            _inBr_ = null;
            return;
        }

        if(_outBr_ == child)
        {
            _outBr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(_inBr_ == oldChild)
        {
            setInBr((PExpression) newChild);
            return;
        }

        if(_outBr_ == oldChild)
        {
            setOutBr((PExpression) newChild);
            return;
        }

    }
}
