/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AMinExpression extends PExpression
{
    private PValue _value_;
    private final LinkedList _comVal_ = new TypedLinkedList(new ComVal_Cast());

    public AMinExpression()
    {
    }

    public AMinExpression(
        PValue _value_,
        List _comVal_)
    {
        setValue(_value_);

        {
            this._comVal_.clear();
            this._comVal_.addAll(_comVal_);
        }

    }
    public Object clone()
    {
        return new AMinExpression(
            (PValue) cloneNode(_value_),
            cloneList(_comVal_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinExpression(this);
    }

    public PValue getValue()
    {
        return _value_;
    }

    public void setValue(PValue node)
    {
        if(_value_ != null)
        {
            _value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _value_ = node;
    }

    public LinkedList getComVal()
    {
        return _comVal_;
    }

    public void setComVal(List list)
    {
        _comVal_.clear();
        _comVal_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_value_)
            + toString(_comVal_);
    }

    void removeChild(Node child)
    {
        if(_value_ == child)
        {
            _value_ = null;
            return;
        }

        if(_comVal_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        for(ListIterator i = _comVal_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class ComVal_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PComVal node = (PComVal) o;

            if((node.parent() != null) &&
                (node.parent() != AMinExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AMinExpression.this))
            {
                node.parent(AMinExpression.this);
            }

            return node;
        }
    }
}
