/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AWhileStatement extends PStatement
{
    private POrComparison _orComparison_;
    private PStatement _statement_;

    public AWhileStatement()
    {
    }

    public AWhileStatement(
        POrComparison _orComparison_,
        PStatement _statement_)
    {
        setOrComparison(_orComparison_);

        setStatement(_statement_);

    }
    public Object clone()
    {
        return new AWhileStatement(
            (POrComparison) cloneNode(_orComparison_),
            (PStatement) cloneNode(_statement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileStatement(this);
    }

    public POrComparison getOrComparison()
    {
        return _orComparison_;
    }

    public void setOrComparison(POrComparison node)
    {
        if(_orComparison_ != null)
        {
            _orComparison_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _orComparison_ = node;
    }

    public PStatement getStatement()
    {
        return _statement_;
    }

    public void setStatement(PStatement node)
    {
        if(_statement_ != null)
        {
            _statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _statement_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_orComparison_)
            + toString(_statement_);
    }

    void removeChild(Node child)
    {
        if(_orComparison_ == child)
        {
            _orComparison_ = null;
            return;
        }

        if(_statement_ == child)
        {
            _statement_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_orComparison_ == oldChild)
        {
            setOrComparison((POrComparison) newChild);
            return;
        }

        if(_statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

    }
}
