/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TDiff extends Token
{
    public TDiff()
    {
        super.setText("!=");
    }

    public TDiff(int line, int pos)
    {
        super.setText("!=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDiff(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDiff(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDiff text.");
    }
}
