/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TFullstop extends Token
{
    public TFullstop()
    {
        super.setText(".");
    }

    public TFullstop(int line, int pos)
    {
        super.setText(".");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TFullstop(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFullstop(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TFullstop text.");
    }
}
