/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TGreq extends Token
{
    public TGreq()
    {
        super.setText(">=");
    }

    public TGreq(int line, int pos)
    {
        super.setText(">=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TGreq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGreq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TGreq text.");
    }
}
