/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TLeeq extends Token
{
    public TLeeq()
    {
        super.setText("<=");
    }

    public TLeeq(int line, int pos)
    {
        super.setText("<=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLeeq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLeeq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLeeq text.");
    }
}
